namespace Core
{
    public enum SpellMechanics
    {
        None,
        Charm,
        Disoriented,
        Disarm,
        Distract,
        Fear,
        Grip,
        Root,
        SlowAttack,
        Silence,
        Sleep,
        Snare,
        Stun,
        Freeze,
        Knockout,
        Bleed,
        Bandage,
        Polymorph,
        Banish,
        Shield,
        Shackle,
        Mount,
        Infected,
        Wounded,
        Horror,
        Invulnerability,
        Interrupt,
        Daze,
        Enraged,
        ImmuneShield,
        Sapped
    }
}
