using System;

namespace Core
{
    [Flags]
    public enum AuraFlags
    {
        None = 0x00,
        Nocaster = 0x01,
        Positive = 0x02,
        Duration = 0x04,
        Scalable = 0x08,
        Negative = 0x10,
    }

    [Flags]
    public enum SpellAuraInterruptFlags : uint
    {
        Hitbyspell = 0x00000001,            // 0    removed when getting hit by a negative spell?
        TakeDamage = 0x00000002,            // 1    removed by any damage
        Cast = 0x00000004,                  // 2    cast any spells
        Move = 0x00000008,                  // 3    removed by any movement
        Turning = 0x00000010,               // 4    removed by any turning
        Jump = 0x00000020,                  // 5    removed by entering combat
        NotMounted = 0x00000040,            // 6    removed by dismounting
        NotAbovewater = 0x00000080,         // 7    removed by entering water
        NotUnderwater = 0x00000100,         // 8    removed by leaving water
        NotSheathed = 0x00000200,           // 9    removed by unsheathing
        Talk = 0x00000400,                  // 10   talk to npc / loot? action on creature
        Use = 0x00000800,                   // 11   mine/use/open action on gameobject
        MeleeAttack = 0x00001000,           // 12   removed by attacking
        SpellAttack = 0x00002000,           // 13   ???
        Transform = 0x00008000,             // 15   removed by transform?
        Mount = 0x00020000,                 // 17   misdirect, aspect, swim speed
        NotSeated = 0x00040000,             // 18   removed by standing up (used by food and drink mostly and sleep/Fake Death like)
        ChangeMap = 0x00080000,             // 19   leaving map/getting teleported
        ImmuneOrLostSelection = 0x00100000, // 20   removed by auras that make you invulnerable, or make other to lose selection on you
        Teleported = 0x00400000,            // 22
        EnterPvpCombat = 0x00800000,        // 23   removed by entering pvp combat
        DirectDamage = 0x01000000,          // 24   removed by any direct damage
        Landing = 0x02000000,               // 25   removed by hitting the ground
        LeaveCombat = 0x80000000,           // 31   removed by leaving combat

        NotVictim = Hitbyspell | TakeDamage | DirectDamage
    }


    public enum AuraRemoveMode
    {
        AuraRemoveNone = 0,
        AuraRemoveByDefault = 1,    // scripted remove, remove by stack with aura with different ids and sc aura remove
        AuraRemoveByCancel,
        AuraRemoveByEnemySpell,     // dispel and absorb aura destroy
        AuraRemoveByExpire,         // aura duration has ended
        AuraRemoveByDeath
    }

    public enum AuraEffectHandleModes
    {
        Default = 0x0,
        Real = 0x01,            // handler applies/removes effect from unit
        SendForClient = 0x02,   // handler sends apply/remove packet to unit
        ChangeAmount = 0x04,    // handler updates effect on target after effect amount change
        Reapply = 0x08,         // handler updates effect on target after aura is reapplied on target
        Stat = 0x10,            // handler updates effect on target when stat removal/apply is needed for calculations by core
        Skill = 0x20,           // handler updates effect on target when skill removal/apply is needed for calculations by core
        SendForClientMask = SendForClient | Real,     // any case handler need to send packet
        ChangeAmountMask = ChangeAmount | Real,       // any case handler applies effect depending on amount
        ChangeAmountSendForClientMask = ChangeAmountMask | SendForClientMask,
        RealOrReapplyMask = Reapply | Real
    }


    public enum AuraType
    {
        None = 0,
        BindSight = 1,
        ModPossess = 2,
        PeriodicDamage = 3,
        Dummy = 4,
        ModConfuse = 5,
        ModCharm = 6,
        ModFear = 7,
        PeriodicHeal = 8,
        ModAttackspeed = 9,
        ModThreat = 10,
        ModTaunt = 11,
        ModStun = 12,
        ModDamageDone = 13,
        ModDamageTaken = 14,
        DamageShield = 15,
        ModStealth = 16,
        ModStealthDetect = 17,
        ModInvisibility = 18,
        ModInvisibilityDetect = 19,
        ObsModHealth = 20,
        ObsModPower = 21,
        ModResistance = 22,
        PeriodicTriggerSpell = 23,
        PeriodicEnergize = 24,
        ModPacify = 25,
        ModRoot = 26,
        ModSilence = 27,
        ReflectSpells = 28,
        ModStat = 29,
        ModSkill = 30,
        ModIncreaseSpeed = 31,
        ModIncreaseMountedSpeed = 32,
        ModDecreaseSpeed = 33,
        ModIncreaseHealth = 34,
        ModIncreaseEnergy = 35,
        ModShapeshift = 36,
        EffectImmunity = 37,
        StateImmunity = 38,
        SchoolImmunity = 39,
        DamageImmunity = 40,
        DispelImmunity = 41,
        ProcTriggerSpell = 42,
        ProcTriggerDamage = 43,
        TrackCreatures = 44,
        TrackResources = 45,
        ModParryPercent = 47,
        ModDodgePercent = 49,
        ModCriticalHealingAmount = 50,
        ModBlockPercent = 51,
        ModWeaponCritPercent = 52,
        PeriodicLeech = 53,
        ModHitChance = 54,
        ModSpellHitChance = 55,
        Transform = 56,
        ModSpellCritChance = 57,
        ModIncreaseSwimSpeed = 58,
        ModDamageDoneCreature = 59,
        ModPacifySilence = 60,
        ModScale = 61,
        PeriodicHealthFunnel = 62,
        PeriodicManaLeech = 64,
        ModCastingSpeedNotStack = 65,
        FeignDeath = 66,
        ModDisarm = 67,
        ModStalked = 68,
        SchoolAbsorb = 69,
        ExtraAttacks = 70,
        ModPowerCostSchoolPct = 72,
        ModPowerCostSchool = 73,
        ReflectSpellsSchool = 74,
        ModLanguage = 75,
        FarSight = 76,
        MechanicImmunity = 77,
        Mounted = 78,
        ModDamagePercentDone = 79,
        ModPercentStat = 80,
        SplitDamagePct = 81,
        WaterBreathing = 82,
        ModBaseResistance = 83,
        ModRegen = 84,
        ModPowerRegen = 85,
        ChannelDeathItem = 86,
        ModDamagePercentTaken = 87,
        ModHealthRegenPercent = 88,
        PeriodicDamagePercent = 89,
        ModDetectRange = 91,
        PreventsFleeing = 92,
        ModUnattackable = 93,
        InterruptRegen = 94,
        Ghost = 95,
        SpellMagnet = 96,
        ManaShield = 97,
        ModSkillTalent = 98,
        ModAttackPower = 99,
        AurasVisible = 100,
        ModResistancePct = 101,
        ModMeleeAttackPowerVersus = 102,
        ModTotalThreat = 103,
        WaterWalk = 104,
        FeatherFall = 105,
        Hover = 106,
        AddFlatModifier = 107,
        AddPctModifier = 108,
        AddTargetTrigger = 109,
        ModPowerRegenPercent = 110,
        AddCasterHitTrigger = 111,
        OverrideClassScripts = 112,
        ModRangedDamageTaken = 113,
        ModRangedDamageTakenPct = 114,
        ModHealing = 115,
        ModRegenDuringCombat = 116,
        ModMechanicResistance = 117,
        ModHealingPct = 118,
        Untrackable = 120,
        Empathy = 121,
        ModOffhandDamagePct = 122,
        ModTargetResistance = 123,
        ModRangedAttackPower = 124,
        ModMeleeDamageTaken = 125,
        ModMeleeDamageTakenPct = 126,
        RangedAttackPowerAttackerBonus = 127,
        ModPossessPet = 128,
        ModSpeedAlways = 129,
        ModMountedSpeedAlways = 130,
        ModRangedAttackPowerVersus = 131,
        ModIncreaseEnergyPercent = 132,
        ModIncreaseHealthPercent = 133,
        ModManaRegenInterrupt = 134,
        ModHealingDone = 135,
        ModHealingDonePercent = 136,
        ModTotalStatPercentage = 137,
        ModMeleeHaste = 138,
        ForceReaction = 139,
        ModRangedHaste = 140,
        ModBaseResistancePct = 142,
        ModResistanceExclusive = 143,
        SafeFall = 144,
        ModPetTalentPoints = 145,
        AllowTamePetType = 146,
        MechanicImmunityMask = 147,
        RetainComboPoints = 148,
        ReducePushback = 149,  //    Reduce Pushback
        ModShieldBlockvaluePct = 150,
        TrackStealthed = 151,  //    Track Stealthed
        ModDetectedRange = 152,  //    Mod Detected Range
        ModStealthLevel = 154,  //    Stealth Level Modifier
        ModWaterBreathing = 155,  //    Mod Water Breathing
        ModReputationGain = 156,  //    Mod Reputation Gain
        PetDamageMulti = 157,  //    Mod Pet Damage
        ModShieldBlockvalue = 158,
        NoPvpCredit = 159,
        ModHealthRegenInCombat = 161,
        PowerBurn = 162,
        ModCritDamageBonus = 163,
        MeleeAttackPowerAttackerBonus = 165,
        ModAttackPowerPct = 166,
        ModRangedAttackPowerPct = 167,
        ModDamageDoneVersus = 168,
        DetectAmore = 170,
        ModSpeedNotStack = 171,
        ModMountedSpeedNotStack = 172,
        ModSpellDamageOfStatPercent = 174,  // by defeult intelect, dependent from SPELL_AURA_MOD_SPELL_HEALING_OF_STAT_PERCENT
        ModSpellHealingOfStatPercent = 175,
        SpiritOfRedemption = 176,
        AOECharm = 177,
        ModAttackerSpellCritChance = 179,
        ModFlatSpellDamageVersus = 180,
        ModResistanceOfStatPercent = 182,
        ModCriticalThreat = 183,
        ModAttackerMeleeHitChance = 184,
        ModAttackerRangedHitChance = 185,
        ModAttackerSpellHitChance = 186,
        ModAttackerMeleeCritChance = 187,
        ModAttackerRangedCritChance = 188,
        ModRating = 189,
        ModFactionReputationGain = 190,
        UseNormalMovementSpeed = 191,
        ModMeleeRangedHaste = 192,
        MeleeSlow = 193,
        ModTargetAbsorbSchool = 194,
        ModTargetAbilityAbsorbSchool = 195,
        ModCooldown = 196,
        ModAttackerSpellAndWeaponCritChance = 197,
        ModXpPct = 200,
        IgnoreCombatResult = 202,
        ModAttackerMeleeCritDamage = 203,
        ModAttackerRangedCritDamage = 204,
        ModSchoolCritDMGTaken = 205,
        ModIncreaseVehicleFlightSpeed = 206,
        ModIncreaseMountedFlightSpeed = 207,
        ModIncreaseFlightSpeed = 208,
        ModMountedFlightSpeedAlways = 209,
        ModVehicleSpeedAlways = 210,
        ModFlightSpeedNotStack = 211,
        ModRageFromDamageDealt = 213,
        ArenaPreparation = 215,
        HasteSpells = 216,
        ModMeleeHaste2 = 217,
        HasteRanged = 218,
        ModManaRegenFromStat = 219,
        ModRatingFromStat = 220,
        ModDetaunt = 221,
        RaidProcFromCharge = 223,
        RaidProcFromChargeWithValue = 225,
        PeriodicDummy = 226,
        PeriodicTriggerSpellWithValue = 227,
        DetectStealth = 228,
        ModAOEDamageAvoidance = 229,
        ModMaxHealth = 230,
        ProcTriggerSpellWithValue = 231,
        MechanicDurationMod = 232,
        ChangeModelForAllHumanoids = 233,  // client-side only
        MechanicDurationModNotStack = 234,
        ModDispelResist = 235,
        ControlVehicle = 236,
        ModSpellDamageOfAttackPower = 237,
        ModSpellHealingOfAttackPower = 238,
        ModScale2 = 239,
        ModExpertise = 240,
        ForceMoveForward = 241,
        ModSpellDamageFromHealing = 242,
        ModFaction = 243,
        ComprehendLanguage = 244,
        ModAuraDurationByDispel = 245,
        ModAuraDurationByDispelNotStack = 246,
        CloneCaster = 247,
        ModCombatResultChance = 248,
        ConvertRune = 249,
        ModIncreaseHealth2 = 250,
        ModEnemyDodge = 251,
        ModSpeedSlowAll = 252,
        ModBlockCritChance = 253,
        ModDisarmOffhand = 254,
        ModMechanicDamageTakenPercent = 255,
        NoReagentUse = 256,
        ModTargetResistBySpellClass = 257,
        ScreenEffect = 260,
        Phase = 261,
        AbilityIgnoreAurastate = 262,
        AllowOnlyAbility = 263,
        ModImmuneAuraApplySchool = 267,
        ModIgnoreTargetResist = 269,
        ModSpellDamageFromCaster = 271,
        IgnoreMeleeReset = 272,
        XRay = 273,
        ModIgnoreShapeshift = 275,
        ModDamageDoneForMechanic = 276,
        ModDisarmRanged = 278,
        InitializeImages = 279,
        ModHonorGainPct = 281,
        ModBaseHealthPct = 282,
        ModHealingReceived = 283,  // Possibly only for some spell family class spells
        Linked = 284,
        ModAttackPowerOfArmor = 285,
        AbilityPeriodicCrit = 286,
        DeflectSpells = 287,
        IgnoreHitDirection = 288,
        PreventDurabilityLoss = 289,
        ModCritPct = 290,
        ModXpQuestPct = 291,
        OpenStable = 292,
        OverrideSpells = 293,
        PreventRegeneratePower = 294,
        SetVehicleID = 296,
        BlockSpellFamily = 297,
        Strangulate = 298,
        ShareDamagePct = 300,
        SchoolHealAbsorb = 301,
        ModDamageDoneVersusAurastate = 303,
        ModFakeInebriate = 304,
        ModMinimumSpeed = 305,
        HealAbsorbTest = 307,
        ModCritChanceForCaster = 308,
        ModResilience = 309,  // NYI
        ModCreatureAOEDamageAvoidance = 310,
        AnimReplacementSet = 312,
        PreventResurrection = 314,
        UnderwaterWalking = 315,
        PeriodicHaste = 316,  // Not used in 4.3.4 (name from 3.3.5a)
        ModSpellPowerPct = 317,
        Mastery = 318,
        ModMeleeHaste3 = 319,
        ModRangedHaste2 = 320,
        ModNoActions = 321,
        InterfereTargetting = 322,
        PhaseGroup = 326,  // Puts the player in all the phases that are in the group with id = miscB
        ProcOnPowerAmount = 328,
        ModRuneRegenSpeed = 329,  // NYI
        CastWhileWalking = 330,
        ForceWeather = 331,
        OverrideActionbarSpells = 332,
        OverrideActionbarSpellsTriggered = 333,  // Spells cast with this override have no cast time or power cost
        ModBlind = 334,  // NYI
        ModFlyingRestrictions = 336,  // NYI
        ModVendorItemsPrices = 337,
        ModDurabilityLoss = 338,
        IncreaseSkillGainChance = 339,  // NYI
        ModResurrectedHealthByGuildMember = 340,  // Increases health gained when resurrected by a guild member by X
        ModSpellCategoryCooldown = 341,  // Modifies cooldown of all spells using affected category
        ModMeleeRangedHaste2 = 342,
        ModMeleeDamageFromCaster = 343,  // NYI
        ModAutoattackDamage = 344,  // NYI
        BypassArmorForCaster = 345,
        EnableAltPower = 346,  // NYI
        ModSpellCooldownByHaste = 347,
        DepositBonusMoneyInGuildBankOnLoot = 348,
        ModCurrencyGain = 349,
        ModGatheringItemsGainedPercent = 350,  // NYI
        ModCamouflage = 353,  // NYI
        EnableBoss1UnitFrame = 357,
        WorgenAlteredForm = 358,
        ProcTriggerSpellCopy = 360,  // Procs the same spell that caused this proc (Dragonwrath, Tarecgosa's Rest)
        OverrideAutoattackWithMeleeSpell = 361,  // NYI
        ModNextSpell = 363,  // Used by 101601 Throw Totem - causes the client to initialize spell cast with specified spell
        MaxFarClipPlane = 365,  // Overrides client's View Distance setting to max("Fair", current_setting) and turns off terrain display
        OverrideAutoattackWithRangedSpell = 367,  // NYI
        EnablePowerBarTimer = 369,
        SetFairFarClip = 370,  // Overrides client's View Distance setting to max("Fair", current_setting)
        ModifyFallDamagePct = 374,  // NYI
        ModCurrencyGainFromSource = 376,  // NYI
        CastWhileWalking2 = 377,  // NYI
        ModGlobalCooldownByHaste = 380,  // Allows melee abilities to benefit from haste GCD reduction
        ModPetStatPct = 382,  // NYI
        IgnoreSpellCooldown = 383,  // NYI
        ChanceOverrideAutoattackWithSpellOnSelf = 385,  // NYI (with triggered spell cast by the initial caster?)
        ModTaxiFlightSpeed = 388,  // NYI
        ShowConfirmationPrompt = 394,
        AreaTrigger = 395,  // NYI
        ProcOnPowerAmount2 = 396,  // missing MicValueB handling, probably OnAmountReach ascending/descending or spell/stack add/remove
        ModSkill2 = 400,
        ModPowerDisplay = 402,
        OverrideSpellVisual = 403,
        OverrideAttackPowerBySpPct = 404,
        ModRatingPct = 405,  // NYI
        ModFear2 = 407,  // NYI
        CanTurnWhileFalling = 409,
        ModMaxCharges = 411,
        ModCooldownByHasteRegen = 416,
        ModGlobalCooldownByHasteRegen = 417,
        ModMaxPower = 418,  // NYI
        ModBaseManaPct = 419,
        ModBattlePetXpPct = 420,  // NYI
        ModAbsorbEffectsAmountPct = 421,  // NYI
        ScalePlayerLevel = 427,  // NYI
        PlayScene = 430,
        ModOverrideZonePvpType = 431,  // NYI
        ModEnvironmentalDamageTaken = 436,  // NYI
        ModMinimumSpeedRate = 437,
        PreloadPhase = 438,  // NYI
        ModMultistrikeDamage = 440,  // NYI
        ModMultistrikeChance = 441,  // NYI
        ModReadiness = 442,  // NYI
        ModLeech = 443,  // NYI
        ModXpFromCreatureType = 447,
        OverridePetSpecs = 451,
        ChargeRecoveryMod = 453,
        ChargeRecoveryMultiplier = 454,
        ModRoot2 = 455,
        ChargeRecoveryAffectedByHaste = 456,
        ChargeRecoveryAffectedByHasteRegen = 457,
        IgnoreDualWieldHitPenalty = 458,  // NYI
        IgnoreMovementForces = 459,  // NYI
        ResetCooldownsOnDuelStart = 460,  // NYI
        ModHealingAndAbsorbFromCaster = 462,  // NYI
        ConvertCritRatingPctToParryRating = 463,  // NYI
        ModAttackPowerOfBonusArmor = 464,  // NYI
        ModBonusArmor = 465,  // NYI
        ModBonusArmorPct = 466,  // Affects bonus armor gain from all sources except base stats
        ModStatBonusPct = 467,  // Affects stat gain from all sources except base stats
        TriggerSpellOnHealthBelowPct = 468,  // Triggers spell when health falls below specified percent value (once, not every time damage is taken below threshold)
        ShowConfirmationPromptWithDifficulty = 469,
        ModVersatility = 471,  // NYI
        PreventDurabilityLossFromCombat = 473,  // Prevents durability loss from dealing/taking damage
        AllowUsingGameobjectsWhileMounted = 475,
        ModCurrencyGainLooted = 476,
        ConvertConsumedRune = 481,
    }
}